from app.models import db, environment, SCHEMA
from sqlalchemy.sql import text
from app.models.trail import Trail


def seed_trails():
    hiking1 = Trail(
        trail_name='Mount Minsi via Appalachian Trail', park='Delaware Water Gap', city='Stroudsburg', state='PA', lat=40.9797353, lng=-75.1415383, category_id=1, length=4.8, elevation_gain=1036, user_id=10, description="The Mount Minsi via Appalachian Trail is a scenic hiking trail located in Delaware Water Gap near the city of Stroudsburg, PA. Spanning approximately 4.8 miles in length, this trail offers outdoor enthusiasts a moderately challenging adventure with an elevation gain of 1036 feet. Hikers can immerse themselves in the natural beauty of the area as they traverse through lush forests and enjoy breathtaking views along the way. With its convenient location and diverse terrain, the Mount Minsi trail is an ideal choice for those seeking an enjoyable and rewarding hiking experience in the Pennsylvania wilderness.", cover_photo="https://alttrails.s3.amazonaws.com/Mount+Minsi.jpg")
    hiking2 = Trail(
        trail_name='Black Bear Wilderness Area Trail', park='Black Bear Wilderness Area', city='Sanford', state='FL', lat=28.8029, lng=81.2695, category_id=1, length=7.3, elevation_gain=29, user_id=9, description="The Black Bear Wilderness Area Trail is a captivating hiking trail situated in the Black Bear Wilderness Area, near the city of Sanford, FL. Stretching across 7.3 miles, this trail offers hikers an immersive experience in a stunning natural setting. With minimal elevation gain of 29 feet, it is suitable for various fitness levels. As hikers traverse the trail, they are treated to breathtaking views of diverse ecosystems, including lush wetlands and vibrant wildlife habitats. The Black Bear Wilderness Area Trail presents an excellent opportunity for outdoor enthusiasts to explore the natural beauty of Florida and appreciate its abundant flora and fauna.", cover_photo="https://alttrails.s3.amazonaws.com/black+bear.jpeg")
    hiking3 = Trail(
        trail_name='Dream Lake Trail', park='Rocky Mountain National Park', city='Estes Park', state='CO', lat=40.30972, lng=-105.65702, category_id=1, length=2, elevation_gain=459, user_id=8, description="The Dream Lake Trail is a captivating hiking trail located in Rocky Mountain National Park, near the city of Estes Park, CO. Spanning 2 miles in length, this trail offers hikers a relatively short but rewarding adventure. With an elevation gain of 459 feet, it provides a moderate challenge and showcases the breathtaking beauty of the Rocky Mountains. Hikers will be enchanted by the trail's picturesque surroundings, including the serene Dream Lake. The trail is known for its stunning alpine scenery, lush forests, and abundant wildlife, making it a must-visit destination for nature enthusiasts. The Dream Lake Trail in Rocky Mountain National Park promises an unforgettable hiking experience amidst the majestic landscapes of Colorado.",  cover_photo="https://alttrails.s3.amazonaws.com/dreamLake.jpg")
    hiking4 = Trail(
        trail_name='Ricketts Glenn Falls Trail Loop', park='Ricketts Glenn State Park', city='Ripple', state='PA', lat=41.3265322, lng=-76.2878003, category_id=1, length=4.1, elevation_gain=866, user_id=7, description="The Ricketts Glenn Falls Trail Loop is a breathtaking hiking trail nestled in Ricketts Glenn State Park, located in Ripple, PA. Covering a distance of 4.1 miles, this trail offers hikers a memorable experience through picturesque landscapes. With an elevation gain of 866 feet, it presents a moderate challenge, rewarding adventurers with awe-inspiring waterfalls and stunning natural beauty. Hikers will have the opportunity to witness the park's iconic 21 waterfalls, including the magnificent Ganoga Falls, as they traverse the trail's well-maintained pathways. The Ricketts Glenn Falls Trail Loop is a must-visit destination for outdoor enthusiasts seeking a captivating hiking experience amidst the enchanting beauty of Pennsylvania's state parks.",  cover_photo="https://alttrails.s3.amazonaws.com/ricketts.jpg")
    hiking5 = Trail(
        trail_name='Mount Yonah Trail', park='Chattahoochee-Oconee National Forest', city='Clevland', state='GA', lat=34.6373228, lng=-83.7256391, category_id=1, length=4.1 , elevation_gain=1453, user_id=6, description="The Mount Yonah Trail is a thrilling hiking trail located in Chattahoochee-Oconee National Forest, near the city of Cleveland, GA. Extending over a distance of 4.1 miles, this trail provides hikers with a challenging and rewarding experience. With an elevation gain of 1453 feet, it offers breathtaking panoramic views of the surrounding forested landscapes and the picturesque Yonah Mountain. As hikers ascend the trail, they will encounter rocky terrain and steep sections, making it suitable for experienced adventurers seeking a more strenuous hike. The Mount Yonah Trail in Chattahoochee-Oconee National Forest is a must-visit destination for outdoor enthusiasts looking for an exhilarating journey amidst the natural beauty of Georgia's wilderness.",  cover_photo="https://alttrails.s3.amazonaws.com/yonah.jpg")
    hiking6 = Trail(
        trail_name='Old Rag Mountain Loop', park='Shenandoah National Park', city='Etlan', state='VA', lat=38.55166, lng=-78.31428, category_id=1, length=9.3 , elevation_gain=2595, user_id=5, description="The Old Rag Mountain Loop is an iconic hiking trail situated in Shenandoah National Park, near the city of Etlan, VA. Spanning a distance of 9.3 miles, this trail offers hikers a challenging and exhilarating adventure. With an elevation gain of 2595 feet, it presents a strenuous climb, rewarding hikers with breathtaking views of the Shenandoah Valley and surrounding peaks. The trail showcases diverse terrain, including rocky outcrops, dense forests, and scenic meadows. As hikers make their way through the loop, they'll encounter thrilling scrambles and the opportunity to explore the famous granite boulders of Old Rag Mountain. The Old Rag Mountain Loop is a must-visit destination for outdoor enthusiasts seeking a memorable and rewarding hike in the picturesque Shenandoah National Park.",  cover_photo="https://alttrails.s3.amazonaws.com/oldRag.jpg")
    hiking7 = Trail(
        trail_name='Rainbow Falls Trail', park='Jones Gap State Park', city='Clevland', state='SC', lat=35.0715, lng=82.5216, category_id=1, length=4.4 , elevation_gain=1181, user_id=4, description="The Rainbow Falls Trail is a stunning hiking trail located in Jones Gap State Park, near the city of Cleveland, SC. Spanning a distance of 4.4 miles, this trail offers hikers a captivating and rewarding experience. With an elevation gain of 1181 feet, it presents a moderate to challenging trek through the scenic Blue Ridge Mountains. The highlight of the trail is the majestic Rainbow Falls, a breathtaking 100-foot waterfall that cascades down a rugged cliff face. As hikers traverse the trail, they'll encounter diverse flora and fauna, serene streams, and peaceful forested surroundings. The Rainbow Falls Trail in Jones Gap State Park is a must-visit for nature enthusiasts looking to immerse themselves in the beauty of South Carolina's natural landscapes.",  cover_photo="https://alttrails.s3.amazonaws.com/rainbowFalls.jpg")
    hiking8 = Trail(
        trail_name='Guadalupe Peak Trail', park='Guadalupe Mountains National Park', city='Salt Flat', state='TX', lat=31.7453, lng=105.0809, category_id=1, length=8.1 , elevation_gain=2949, user_id=3, description="The Guadalupe Peak Trail is an awe-inspiring hiking trail located in Guadalupe Mountains National Park, near the city of Salt Flat, TX. Stretching across 8.1 miles, this trail offers hikers a challenging yet rewarding adventure. With an elevation gain of 2949 feet, it leads to the highest point in Texas, the majestic Guadalupe Peak. As hikers ascend the trail, they'll be treated to breathtaking views of the surrounding desert landscapes and rugged mountain ranges. The trail showcases diverse flora and fauna, including the park's iconic coniferous forests and unique desert vegetation. The Guadalupe Peak Trail in Guadalupe Mountains National Park is a must-visit for outdoor enthusiasts seeking a memorable and rewarding hike in the Lone Star State.",  cover_photo="https://alttrails.s3.amazonaws.com/guadalupe.jpg")
    hiking9 = Trail(
        trail_name='Riverscene Trail', park='Castlewood State Park', city='Ballwin', state='MO', lat=38.5951, lng=90.5462, category_id=1, length=3.4 , elevation_gain=282, user_id=2, description="The Riverscene Trail is a scenic hiking trail located in Castlewood State Park, near the city of Ballwin, MO. Spanning 3.4 miles, this trail offers hikers a picturesque and leisurely stroll along the banks of the Meramec River. With a modest elevation gain of 282 feet, it is suitable for hikers of all skill levels. As hikers explore the trail, they will be treated to beautiful views of the river, tranquil wooded areas, and charming meadows. The Riverscene Trail is an ideal choice for nature lovers seeking a peaceful and enjoyable hike in the serene landscapes of Castlewood State Park.",  cover_photo="https://alttrails.s3.amazonaws.com/riverscene.jpg")
    hiking10 = Trail(
        trail_name='Bear Mountain Loop Trail', park='Bear Mountain State Park', city='Ft. Clinton', state='NY', lat=41.31789, lng=-73.99399, category_id=1, length=3.8 , elevation_gain=1154, user_id=1, description="The Bear Mountain Loop Trail is a scenic hiking trail located in Bear Mountain State Park, near the city of Ft. Clinton, NY. Covering a distance of 3.8 miles, this trail offers hikers a rewarding and invigorating experience. With an elevation gain of 1154 feet, it presents a moderate challenge, rewarding hikers with breathtaking panoramic views of the Hudson River and the surrounding landscapes. As hikers traverse the trail, they'll encounter a mix of rocky terrain, serene forests, and charming meadows. The Bear Mountain Loop Trail in Bear Mountain State Park is a popular choice for outdoor enthusiasts looking to enjoy nature, explore historic sites, and indulge in the beauty of New York's scenic wilderness.",  cover_photo="https://alttrails.s3.amazonaws.com/bearMountainLoop.jpg")
    hiking11 = Trail(
        trail_name='Cornish Estate Trail', park='Hudson Highlands State Park Preserve', city='Cold Spring', state='NY', lat=41.4201, lng=73.9546, category_id=1, length=1.8 , elevation_gain=190, user_id=10, description="The Cornish Estate Trail is a picturesque hiking trail located in Hudson Highlands State Park Preserve, near the city of Cold Spring, NY. Spanning a distance of 1.8 miles, this trail offers hikers a short yet delightful experience. With a gentle elevation gain of 190 feet, it is suitable for hikers of various fitness levels. As hikers explore the trail, they will discover remnants of the historic Cornish Estate, including the ruins of a mansion and beautiful gardens. The trail meanders through serene woodlands and provides scenic views of the Hudson River. The Cornish Estate Trail is a perfect choice for a leisurely hike amidst the natural beauty and rich history of Hudson Highlands State Park Preserve.",  cover_photo="https://alttrails.s3.amazonaws.com/cornishEstate.jpeg")
    hiking12 = Trail(
        trail_name='Great Blue Hill via Skyline Trail', park='Blue Hill Reservation', city='Milton', state='MA', lat=42.2134586, lng=-71.1123258, category_id=1, length=3.1, elevation_gain=813, user_id=9, description="The Great Blue Hill via Skyline Trail is an exhilarating hiking trail located in Blue Hill Reservation, near the city of Milton, MA. Stretching across 3.1 miles, this trail offers hikers a rewarding and scenic adventure. With an elevation gain of 813 feet, it presents a moderate challenge, leading hikers to the summit of Great Blue Hill. Along the trail, hikers will encounter diverse terrain, including rocky paths, lush forests, and panoramic vistas. The highlight of the trail is the breathtaking views of the Boston skyline and the surrounding landscape from the summit. The Great Blue Hill via Skyline Trail in Blue Hill Reservation is a must-visit destination for outdoor enthusiasts seeking a memorable hike in the picturesque beauty of Massachusetts.",  cover_photo="https://alttrails.s3.amazonaws.com/greatBlueHill.jpeg")
    hiking13 = Trail(
        trail_name='Little Grand Canyon Trail', park='Shawnee National Forest', city='Pomona', state='IL', lat=37.6281, lng=89.3368, category_id=1, length=3.4, elevation_gain=508, user_id=8, description="The Little Grand Canyon Trail is a captivating hiking trail located in Shawnee National Forest, near the city of Pomona, IL. Spanning 3.4 miles, this trail offers hikers a scenic and unique experience. With an elevation gain of 508 feet, it presents a moderate challenge, rewarding hikers with breathtaking views of the rugged canyon walls and lush vegetation. The trail takes hikers through a picturesque landscape carved by the erosive forces of nature, resembling a miniature version of the iconic Grand Canyon. As hikers explore the trail, they'll encounter stunning rock formations, cascading waterfalls, and peaceful streams. The Little Grand Canyon Trail in Shawnee National Forest is a must-visit destination for outdoor enthusiasts looking to immerse themselves in the natural beauty of Illinois' hidden gem.",  cover_photo="https://alttrails.s3.amazonaws.com/littleGrandCanyon.jpg")
    hiking14 = Trail(
        trail_name='Devils Bridge Trail', park='Coconino National Forest', city='Sedona', state='AZ', lat=34.9028, lng=-111.81374, category_id=1, length=3.9 , elevation_gain=521, user_id=7, description="The Devils Bridge Trail is a spectacular hiking trail located in Coconino National Forest, near the city of Sedona, AZ. Covering a distance of 3.9 miles, this trail offers hikers an unforgettable adventure. With an elevation gain of 521 feet, it presents a moderate challenge, leading hikers to the mesmerizing Devils Bridge, a natural sandstone arch. As hikers make their way along the trail, they'll be treated to stunning red rock formations, scenic vistas, and breathtaking views of the surrounding desert landscape. The highlight of the trail is the opportunity to walk across the impressive Devils Bridge, providing an exhilarating experience and fantastic photo opportunities. The Devils Bridge Trail in Coconino National Forest is a must-visit for outdoor enthusiasts seeking an extraordinary hike amidst the majestic beauty of Sedona, Arizona.",  cover_photo="https://alttrails.s3.amazonaws.com/devilsBridge.jpeg")
    hiking15 = Trail(
        trail_name='Tubbs Hill', park='Tubbs Hill Park', city="Coeur d'Alene", state='ID', lat=47.6735, lng=116.7812, category_id=1, length=2.1, elevation_gain=291, user_id=6, description="The Tubbs Hill trail is a scenic hiking trail located in Tubbs Hill Park, situated in the city of Coeur d'Alene, ID. Stretching across 2.1 miles, this trail offers hikers a refreshing and enjoyable experience. With an elevation gain of 291 feet, it presents a moderate hike suitable for all skill levels. As hikers explore the trail, they will be immersed in the natural beauty of the area, including lush forests, rocky cliffs, and picturesque views of Lake Coeur d'Alene. The Tubbs Hill trail is a popular choice for nature lovers seeking a tranquil and accessible hike in the heart of Coeur d'Alene, Idaho.",  cover_photo="https://alttrails.s3.amazonaws.com/tubbsHill.jpg")
    biking1 = Trail(
        trail_name='Pulpit Rock and Pinnacle Loop', park='Appalachian National Scenic Trail', city='Hamburg', state='PA', lat=40.59654, lng=-75.93164, category_id=2, length=9.2, elevation_gain=1259, user_id=5, description="The Pulpit Rock and Pinnacle Loop is an exhilarating biking trail located in the Appalachian National Scenic Trail, near the city of Hamburg, PA. Spanning a distance of 9.2 miles, this trail offers bikers a thrilling and challenging ride. With an elevation gain of 1259 feet, it presents a moderate to strenuous biking experience, showcasing the scenic beauty of the area. As bikers navigate the trail, they'll be rewarded with awe-inspiring views from both Pulpit Rock and Pinnacle overlooks, featuring breathtaking vistas of the surrounding valleys and rolling hills. The Pulpit Rock and Pinnacle Loop is a must-visit destination for cycling enthusiasts seeking an adventurous and picturesque ride through the captivating landscapes of the Appalachian Mountains.",  cover_photo="https://alttrails.s3.amazonaws.com/pulpittRock.jpg")
    biking2 = Trail(
        trail_name='Quiet Waters Mountain Bike Trail', park='Quiet Waters Park', city='Deerfield Beach', state='FL', lat=26.3184, lng=80.0998, category_id=2, length=4.6, elevation_gain=42, user_id=4, description="The Quiet Waters Mountain Bike Trail is a thrilling biking trail located in Quiet Waters Park, near the city of Deerfield Beach, FL. Spanning a distance of 4.6 miles, this trail offers bikers an exciting and exhilarating ride. With a gentle elevation gain of 42 feet, it provides a relatively flat terrain suitable for bikers of various skill levels. As bikers traverse the trail, they'll enjoy the scenic beauty of the park, including lush forests, serene lakes, and charming wildlife. The Quiet Waters Mountain Bike Trail is a perfect choice for biking enthusiasts looking to have a fun-filled adventure in the beautiful natural surroundings of Deerfield Beach, Florida.",  cover_photo="https://alttrails.s3.amazonaws.com/quietWaters.jpeg")
    biking3 = Trail(
        trail_name='Red Rocks and Morrison Slide Trails', park='Matthews Winters Open Space Park', city='Morrison', state='CO', lat=39.6536, lng=105.1911, category_id=2, length=3, elevation_gain=679, user_id=3, description="The Red Rocks and Morrison Slide Trails are exhilarating biking trails located in Matthews Winters Open Space Park, near the city of Morrison, CO. Combining the Red Rocks Trail and the Morrison Slide Trail, this biking experience covers a distance of 3 miles, offering bikers an exciting and challenging ride. With an elevation gain of 679 feet, it provides a moderately steep terrain, perfect for intermediate to advanced bikers. As bikers pedal through the trails, they'll be rewarded with stunning views of the iconic Red Rocks Park and the breathtaking Morrison Slide formation. The Red Rocks and Morrison Slide Trails in Matthews Winters Open Space Park are a must-visit destination for biking enthusiasts seeking an adrenaline-pumping adventure amidst the majestic landscapes of Colorado.",  cover_photo="https://alttrails.s3.amazonaws.com/redRocks.jpg")
    biking4 = Trail(
        trail_name='Trexler Border Trail', park='Trexler Nature Preserve', city='Schnecksville', state='PA', lat=40.6749, lng=75.6179, category_id=2, length=8.9, elevation_gain=1371, user_id=2, description="The Trexler Border Trail is an exciting and challenging biking trail located in Trexler Nature Preserve, near the city of Schnecksville, PA. Covering a distance of 8.9 miles, this trail offers bikers a thrilling and adventurous ride. With an elevation gain of 1371 feet, it presents a moderately steep and varied terrain that caters to intermediate to advanced bikers. As bikers traverse the trail, they'll be surrounded by the natural beauty of the preserve, including scenic woodlands, meadows, and picturesque views. The Trexler Border Trail is a must-visit destination for biking enthusiasts looking to test their skills and enjoy a memorable ride in the captivating landscapes of Schnecksville, Pennsylvania.",  cover_photo="https://alttrails.s3.amazonaws.com/trexler.jpg")
    biking5 = Trail(
        trail_name='Iron Hill Trail', park='Red Top Mountain State Park', city='Cartersville', state='GA', lat=34.1651, lng=84.7999, category_id=2, length=3.4, elevation_gain=141, user_id=1, description="The Iron Hill Trail is an exhilarating biking trail located in Red Top Mountain State Park, near the city of Cartersville, GA. Stretching across 3.4 miles, this trail offers bikers a thrilling and dynamic ride. With an elevation gain of 141 feet, it provides a moderately challenging terrain suitable for bikers of various skill levels. As bikers pedal through the trail, they'll be surrounded by the natural beauty of the park, including dense forests, scenic overlooks, and serene lakeside views. The Iron Hill Trail is a popular choice for biking enthusiasts seeking an adventurous and scenic ride in the charming landscapes of Cartersville, Georgia.",  cover_photo="https://alttrails.s3.amazonaws.com/ironHill.jpg")
    biking6 = Trail(
        trail_name='Buttermilk Trail', park='James River Park', city='Richmond', state='VA', lat=37.5407, lng=77.4360, category_id=2, length=4.5, elevation_gain=410, user_id=10, description="The Buttermilk Trail is an exciting biking trail located in James River Park, in the city of Richmond, VA. Spanning a distance of 4.5 miles, this trail offers bikers a thrilling and enjoyable ride. With an elevation gain of 410 feet, it presents a moderate challenge, making it suitable for bikers of various skill levels. As bikers navigate the trail, they'll be treated to picturesque views of the James River, rocky outcrops, and lush forests. The Buttermilk Trail is known for its flowy singletrack sections and technical features, providing an exciting and dynamic biking experience. It is a popular choice among biking enthusiasts in Richmond, Virginia, looking to explore the natural beauty of James River Park on two wheels.",  cover_photo="https://alttrails.s3.amazonaws.com/buttermilk.jpg")
    biking7 = Trail(
        trail_name='Sulphur Springs Trail', park='Paris Mountain State Park', city='Greenville', state='SC', lat=34.8526, lng=82.3940, category_id=2, length=4.5, elevation_gain=695, user_id=9, description="The Sulphur Springs Trail is an exhilarating biking trail located in Paris Mountain State Park, near the city of Greenville, SC. Covering a distance of 4.5 miles, this trail offers bikers a thrilling and challenging ride. With an elevation gain of 695 feet, it presents a moderately steep terrain that will test the skills of intermediate to advanced bikers. As bikers pedal through the trail, they'll be immersed in the natural beauty of the park, including dense forests, babbling streams, and scenic overlooks. The Sulphur Springs Trail is known for its technical features, rocky sections, and rewarding descents, providing an exciting and dynamic biking experience. It is a popular choice for biking enthusiasts in Greenville, South Carolina, looking to enjoy a memorable ride in the stunning surroundings of Paris Mountain State Park.",  cover_photo="https://alttrails.s3.amazonaws.com/sulpherSprings.jpg")
    biking8 = Trail(
        trail_name='The Lighthouse Trail', park='Palo Duro Canyon State Park', city='Canyon', state='TX', lat=34.9373, lng=101.6589, category_id=2, length=5.8, elevation_gain=521, user_id=8, description="The Lighthouse Trail is an invigorating biking trail located in Palo Duro Canyon State Park, near the city of Canyon, TX. Spanning a distance of 5.8 miles, this trail offers bikers an exhilarating and scenic ride. With an elevation gain of 521 feet, it presents a moderately challenging terrain that will delight intermediate-level bikers. As bikers pedal through the trail, they'll be treated to breathtaking views of the towering red rock formations and rugged canyon landscapes that make Palo Duro Canyon State Park famous. The highlight of the trail is the iconic Lighthouse formation, a natural rock tower that serves as a stunning backdrop to the ride. The Lighthouse Trail is a must-visit destination for biking enthusiasts seeking an adventurous and picturesque biking experience in the magnificent Palo Duro Canyon State Park.",  cover_photo="https://alttrails.s3.amazonaws.com/lighthouseTrail.jpg")
    biking9 = Trail(
        trail_name='Grotpeter Trail', park='Castlewood State Park', city='Valley Park', state='MO', lat=38.5492, lng=90.4926, category_id=2, length=4.8, elevation_gain=380, user_id=7, description="The Grotpeter Trail is a thrilling biking trail located in Castlewood State Park, near the city of Valley Park, MO. Extending for 4.8 miles, this trail offers bikers an exciting and dynamic ride. With an elevation gain of 380 feet, it presents a moderately challenging terrain suitable for intermediate-level bikers. As bikers navigate the trail, they'll be immersed in the natural beauty of the park, including dense forests, scenic overlooks, and the picturesque Meramec River. The Grotpeter Trail is known for its twists and turns, technical sections, and fast descents, providing an adrenaline-pumping biking experience. It is a popular choice for biking enthusiasts in Valley Park, Missouri, looking to explore the captivating landscapes of Castlewood State Park on two wheels.",  cover_photo="https://alttrails.s3.amazonaws.com/grotpeter.jpg")
    biking10 = Trail(
        trail_name='Scarface Mountain', park='Saranac Lakes Wild Forest', city='Ray Brook', state='NY', lat=44.3002, lng=74.0830, category_id=2, length=7.4, elevation_gain=1584, user_id=6, description="The Scarface Mountain trail is a thrilling biking trail located in the Saranac Lakes Wild Forest, near the city of Ray Brook, NY. Spanning a distance of 7.4 miles, this trail offers bikers an adventurous and challenging ride. With an elevation gain of 1584 feet, it presents a steep and demanding terrain that will test the skills of experienced bikers. As bikers pedal along the trail, they'll be rewarded with stunning views of the surrounding Adirondack Mountains and the pristine wilderness of the Saranac Lakes region. The Scarface Mountain trail is known for its technical sections, rocky terrain, and rewarding descents, providing a truly exhilarating biking experience. It is a popular choice for biking enthusiasts in Ray Brook, New York, seeking an adrenaline-pumping adventure amidst the natural beauty of the Saranac Lakes Wild Forest.",  cover_photo="https://alttrails.s3.amazonaws.com/scarface.jpg")
    biking11 = Trail(
        trail_name='Marcy Dam Trail', park='High Peaks Wilderness', city='Lake Placid', state='NY', lat=44.2795, lng=73.9799, category_id=2, length=4.3, elevation_gain=446, user_id=5, description="The Marcy Dam Trail is an exciting biking trail located in the High Peaks Wilderness, near the city of Lake Placid, NY. Covering a distance of 4.3 miles, this trail offers bikers a thrilling and scenic ride. With an elevation gain of 446 feet, it presents a moderately challenging terrain suitable for bikers of various skill levels. As bikers traverse the trail, they'll be immersed in the beauty of the Adirondack Mountains, passing through dense forests, alongside babbling brooks, and enjoying picturesque views of Marcy Dam. The Marcy Dam Trail is known for its mix of smooth sections and moderate technical challenges, making it an enjoyable and rewarding biking experience. It is a popular choice among biking enthusiasts in Lake Placid, New York, seeking a memorable ride in the breathtaking landscapes of the High Peaks Wilderness.",  cover_photo="https://alttrails.s3.amazonaws.com/marcyDam58.jpg")
    biking12 = Trail(
        trail_name='Battle Road Trail', park='Minute Man National Historic Park', city='Concord', state='MA', lat=42.4604, lng=71.3489, category_id=2, length=4.6, elevation_gain=239, user_id=4, description="The Battle Road Trail is a captivating biking trail located in Minute Man National Historic Park, near the city of Concord, MA. Stretching for 4.6 miles, this trail offers bikers a historic and scenic ride. With an elevation gain of 239 feet, it presents a moderately challenging terrain suitable for riders of various skill levels. As bikers pedal along the trail, they'll be transported back in time to the American Revolutionary War era, passing by significant landmarks and battle sites. The Battle Road Trail showcases the natural beauty of the park, including meadows, woodlands, and scenic vistas. Bikers will also have the opportunity to explore historical monuments and learn about the rich history of the area. The Battle Road Trail is a popular choice for biking enthusiasts in Concord, Massachusetts, seeking a combination of outdoor recreation and cultural immersion in the remarkable Minute Man National Historic Park.",  cover_photo="https://alttrails.s3.amazonaws.com/battleRoad60.jpg")
    running1 = Trail(
        trail_name='Hawk Falls Trail', park='Hickory Run State Park', city='Albrightsville', state='PA', lat=41.0145, lng=75.6010, category_id=3, length=1.2, elevation_gain=134, user_id=3, description="The Hawk Falls Trail is a scenic running trail nestled in Hickory Run State Park, near the city of Albrightsville, PA. Spanning a distance of 1.2 miles, this trail provides runners with a short but invigorating route. With an elevation gain of 134 feet, it offers a moderate challenge suitable for runners of varying fitness levels. As runners make their way along the trail, they will be treated to breathtaking views of the surrounding forest, lush greenery, and the tranquil sounds of cascading water. The highlight of the Hawk Falls Trail is the majestic Hawk Falls, a stunning waterfall that serves as a rewarding sight at the end of the run. This trail is a popular choice among running enthusiasts in Albrightsville, Pennsylvania, who seek a quick yet scenic escape into nature and a refreshing workout in Hickory Run State Park.",  cover_photo="https://alttrails.s3.amazonaws.com/hawkFalls62.jpg")
    running2 = Trail(
        trail_name='Weedon Island Preserve Trail', park='Weedon Island Preserve', city='St. Petersburg', state='FL', lat=27.7676, lng=82.6403, category_id=3, length=4.3, elevation_gain=9, user_id=2, description="The Weedon Island Preserve Trail is a picturesque running trail located within the serene Weedon Island Preserve in St. Petersburg, FL. Extending for 4.3 miles, this trail offers runners a tranquil and scenic route. With a minimal elevation gain of 9 feet, it provides a flat and easy terrain suitable for runners of all levels. As runners explore the trail, they'll be surrounded by the natural beauty of the preserve, including lush mangrove forests, marshes, and coastal habitats. The Weedon Island Preserve Trail is known for its serene atmosphere, abundant wildlife sightings, and captivating views of Tampa Bay. It is a popular choice among running enthusiasts in St. Petersburg, Florida, seeking a peaceful and rejuvenating running experience amidst the stunning landscapes of Weedon Island Preserve.",  cover_photo="https://alttrails.s3.amazonaws.com/weedon64.jpg")
    running3 = Trail(
        trail_name='Royal Arch Trail', park='Chautauqua Trailhead', city='Boulder', state='CO', lat=39.9845, lng=105.29152, category_id=3, length=3.4, elevation_gain=1469, user_id=1, description="The Royal Arch Trail is an exhilarating running trail located at the Chautauqua Trailhead in Boulder, CO. Stretching for 3.4 miles, this trail offers runners a challenging and rewarding experience. With an impressive elevation gain of 1469 feet, it presents a steep and demanding terrain that will put runners' endurance to the test. As runners ascend the trail, they'll be treated to breathtaking views of Boulder's iconic Flatirons and the surrounding Rocky Mountains. The highlight of the Royal Arch Trail is the majestic Royal Arch, a natural sandstone arch formation that serves as a scenic reward at the end of the run. This trail is a popular choice among running enthusiasts in Boulder, Colorado, seeking a thrilling workout and the opportunity to immerse themselves in the stunning beauty of Chautauqua Park.",  cover_photo="https://alttrails.s3.amazonaws.com/royalArch66.jpg")
    running4 = Trail(
        trail_name='Wissahickon Gorge North Loop', park='Wissahickon Valley Park', city='Lafayette Hill', state='PA', lat=40.0927, lng=75.2532, category_id=3, length=5.4, elevation_gain=738, user_id=10, description="The Wissahickon Gorge North Loop is a scenic running trail located in Wissahickon Valley Park, near Lafayette Hill, PA. Spanning a distance of 5.4 miles, this trail offers runners a diverse and invigorating route. With an elevation gain of 738 feet, it presents a moderate challenge, combining rolling hills and some steep sections. As runners navigate through the trail, they'll be surrounded by the natural beauty of the Wissahickon Gorge, characterized by lush forests, picturesque creeks, and rocky outcroppings. The trail provides stunning views of the Wissahickon Creek and its serene surroundings. Runners will also pass by historic landmarks and charming stone bridges, adding a touch of heritage to their run. The Wissahickon Gorge North Loop is a popular choice among running enthusiasts in Lafayette Hill, Pennsylvania, seeking a challenging and scenic workout in the picturesque Wissahickon Valley Park.",  cover_photo="https://alttrails.s3.amazonaws.com/wissahickon68.jpg")
    running5 = Trail(
        trail_name='Raven Cliff Falls Trail', park='Raven Cliffs Wilderness', city='Helen', state='GA', lat=34.723182, lng=83.82333, category_id=3, length=4.9, elevation_gain=623, user_id=9, description="The Raven Cliff Falls Trail is a captivating running trail nestled within the scenic Raven Cliffs Wilderness near Helen, GA. Spanning a distance of 4.9 miles, this trail offers runners a captivating and immersive experience. With an elevation gain of 623 feet, it presents a moderate challenge, incorporating both gradual inclines and some steeper sections. As runners traverse the trail, they'll be surrounded by the lush beauty of the wilderness, including dense forests, tranquil streams, and vibrant flora. The highlight of the Raven Cliff Falls Trail is the stunning Raven Cliff Falls, a breathtaking waterfall cascading into a serene pool. Runners can take a moment to appreciate the natural beauty and soothing sounds of the falls before continuing their run. The Raven Cliff Falls Trail is a popular choice among running enthusiasts in Helen, Georgia, seeking a scenic and refreshing escape into nature's embrace in the picturesque Raven Cliffs Wilderness.",  cover_photo="https://alttrails.s3.amazonaws.com/70.jpg")
    running6 = Trail(
        trail_name='Dragons Tooth Trail', park='Jefferson National Forest', city='Catawba', state='VA', lat=37.3827, lng=80.1097, category_id=3, length=4.5, elevation_gain=1256, user_id=8, description="The Dragons Tooth Trail is a thrilling running trail located within Jefferson National Forest, near Catawba, VA. Stretching for 4.5 miles, this trail offers runners a challenging and exhilarating adventure. With an elevation gain of 1256 feet, it presents a steep and demanding terrain that tests runners' endurance and strength. As runners ascend the trail, they'll be rewarded with stunning panoramic views of the surrounding forested mountains. The highlight of the Dragons Tooth Trail is the iconic rock formation known as Dragons Tooth, which resembles a dragon's tooth emerging from the earth. Runners can choose to climb the rock for an additional challenge and enjoy breathtaking views from the top. The Dragons Tooth Trail is a popular choice among running enthusiasts in Catawba, Virginia, seeking a thrilling and scenic trail run in the majestic Jefferson National Forest.",  cover_photo="https://alttrails.s3.amazonaws.com/72.jpg")
    running7 = Trail(
        trail_name='Brissy Ridge', park='Paris Mountain State Park', city='Freenville', state='SC', lat=34.8546, lng=82.3920, category_id=3, length=2.2, elevation_gain=485, user_id=7, description="The Brissy Ridge is a picturesque running trail situated within Paris Mountain State Park, near Greenville, SC. Covering a distance of 2.2 miles, this trail offers runners a delightful and invigorating experience. With an elevation gain of 485 feet, it provides a moderate challenge, combining both gentle slopes and some steeper sections. As runners traverse the trail, they will be immersed in the natural beauty of the park, including lush forests, meandering streams, and scenic overlooks. The Brissy Ridge offers captivating views of the surrounding landscape, showcasing the park's rolling hills and vibrant foliage. Runners can take a moment to appreciate the tranquility of the park and enjoy the harmonious blend of nature and running. The Brissy Ridge is a popular choice among running enthusiasts in Greenville, South Carolina, seeking a refreshing and scenic run amidst the idyllic surroundings of Paris Mountain State Park.",  cover_photo="https://alttrails.s3.amazonaws.com/74.jpg")
    running8 = Trail(
        trail_name='Emory Peak Trail', park='Big Bend National Forest', city='Terlingua', state='TX', lat=29.3216, lng=103.6160, category_id=3, length=9.8, elevation_gain=2493, user_id=6, description="The Emory Peak Trail is a challenging and rewarding running trail located in Big Bend National Park, near Terlingua, TX. Spanning a distance of 9.8 miles, this trail offers runners a thrilling adventure through diverse landscapes and breathtaking vistas. With an elevation gain of 2493 feet, the trail presents steep inclines and rocky terrain, testing runners' endurance and determination. As runners ascend to the summit of Emory Peak, the highest point in the park, they are rewarded with panoramic views of the surrounding Chisos Mountains and the vast expanse of the national park. The trail winds through lush canyons, traverses rocky outcrops, and meanders through dense forests, providing a captivating and ever-changing running experience. The Emory Peak Trail is a favorite among avid trail runners seeking a challenging and awe-inspiring run in the rugged beauty of Big Bend National Park.",  cover_photo="https://alttrails.s3.amazonaws.com/76.jpg")
    walking1 = Trail(
        trail_name='Mount Misery Trail', park='Valley Forge National Historical Park', city='Chesterbrook', state='PA', lat=40.0757, lng=75.4591, category_id=4, length=2.9, elevation_gain=675, user_id=5, description="The Mount Misery Trail is a serene walking trail located within the scenic Valley Forge National Historical Park in Chesterbrook, PA. With a length of 2.9 miles, this trail offers walkers a leisurely and enjoyable experience amidst the historical charm of the park. The trail gently winds through the picturesque landscape, showcasing the park's lush forests, rolling hills, and historic landmarks. With an elevation gain of 675 feet, walkers can enjoy a moderate workout while immersing themselves in the natural beauty of the surroundings. Along the trail, walkers can also explore significant historical sites, including remnants of Revolutionary War encampments and interpretive signage that sheds light on the park's rich history. The Mount Misery Trail provides a peaceful retreat for individuals seeking a refreshing walk in a historically significant and scenic setting.",  cover_photo="https://alttrails.s3.amazonaws.com/78.jpg")
    walking2 = Trail(
        trail_name='Kolokee Loop Trail', park='Little Big Econ State Forest', city='Geneva', state='FL', lat=28.7397, lng=81.1151, category_id=4, length=5.1, elevation_gain=78, user_id=4, description="The Kolokee Loop Trail is a picturesque walking trail nestled within the natural beauty of Little Big Econ State Forest in Geneva, FL. Spanning a length of 5.1 miles, this trail offers walkers a delightful journey through diverse ecosystems and serene landscapes. With a gentle elevation gain of 78 feet, the trail provides a leisurely and accessible walking experience suitable for all skill levels. As walkers traverse the trail, they will encounter enchanting forests, meandering rivers, and tranquil wetlands teeming with wildlife. The Kolokee Loop Trail also offers several scenic viewpoints and resting spots, allowing walkers to pause and appreciate the serenity of the surroundings. Whether it's observing native bird species, enjoying the tranquility of the forest, or simply relishing the fresh air, this trail provides a rejuvenating and immersive experience in the heart of Little Big Econ State Forest.",  cover_photo="https://alttrails.s3.amazonaws.com/80.jpg")
    walking3 = Trail(
        trail_name='Green Mountain Trail', park='William F Hayden Green Mountain Park', city='Denver', state='CO', lat=39.7392, lng=104.9903, category_id=4, length=6.4, elevation_gain=1082, user_id=3, description="The Green Mountain Trail is a scenic walking trail located in William F Hayden Green Mountain Park, near Denver, CO. Spanning a length of 6.4 miles, this trail offers walkers a diverse and immersive experience amidst the natural beauty of the area. With an elevation gain of 1082 feet, the trail provides a moderate challenge for walkers seeking a bit of a workout. As walkers ascend the trail, they will be rewarded with stunning panoramic views of the surrounding landscapes, including the picturesque Denver skyline and the majestic Rocky Mountains. The Green Mountain Trail meanders through lush forests, open meadows, and rocky terrains, showcasing the region's rich biodiversity. Along the way, walkers may encounter a variety of wildlife and have the opportunity to observe native plant species. Whether it's enjoying the peaceful serenity of nature or staying active in a beautiful setting, the Green Mountain Trail offers a wonderful walking experience for nature enthusiasts of all levels.",  cover_photo="https://alttrails.s3.amazonaws.com/82.jpg")
    walking4 = Trail(
        trail_name='Schuylkill River Trail', park='Fairmount Park', city='Philadelphia', state='PA', lat=39.9526, lng=75.1652, category_id=4, length=24.7, elevation_gain=485, user_id=2, description="The Schuylkill River Trail is a popular walking trail that winds through Fairmount Park in Philadelphia, PA. Stretching over a distance of 24.7 miles, this trail offers walkers a picturesque journey along the banks of the Schuylkill River. With a relatively flat terrain and an elevation gain of 485 feet, it provides an enjoyable and accessible walking experience for people of all ages and fitness levels. The trail showcases the natural beauty of the area, with scenic views of the river, lush greenery, and charming park landscapes. Along the way, walkers can also explore historical sites, cultural landmarks, and recreational amenities. The Schuylkill River Trail is a beloved destination for walkers looking to immerse themselves in the vibrant atmosphere of Philadelphia while enjoying the tranquility of nature.",  cover_photo="https://alttrails.s3.amazonaws.com/84.jpg")
    walking5 = Trail(
        trail_name='Amicalola Falls', park='Amicalola Falls State Park', city='Dawsonville', state='GA', lat=34.4212, lng=84.1191, category_id=4, length=0.3, elevation_gain=242, user_id=1, description="The Amicalola Falls trail is a delightful walking trail located in Amicalola Falls State Park, Dawsonville, GA. This short but scenic trail spans a length of 0.3 miles and offers visitors the opportunity to witness the breathtaking beauty of Amicalola Falls, which is one of the tallest cascading waterfalls in the Southeastern United States. As walkers traverse the trail, they will be greeted by the mesmerizing sights and sounds of the rushing waterfall and the surrounding lush forest. With an elevation gain of 242 feet, the trail provides a moderate challenge, making it suitable for walkers of various fitness levels. Whether it's a peaceful stroll or a refreshing hike, the Amicalola Falls trail promises an unforgettable experience in nature's embrace.",  cover_photo="https://alttrails.s3.amazonaws.com/86.jpg")
    walking6 = Trail(
        trail_name='Great Falls Overlook Trail', park='Chesapeake Canal National historical Park', city='Great Falls', state='VA', lat=38.9982, lng=77.2883, category_id=4, length=1.4, elevation_gain=45, user_id=10, description="The Great Falls Overlook Trail, located in Chesapeake and Ohio Canal National Historical Park, Great Falls, VA, is a picturesque walking trail offering stunning views of the majestic Great Falls. Stretching for 1.4 miles, this trail takes visitors on a leisurely stroll through the park's scenic landscape. Along the way, walkers will encounter lush vegetation, tranquil river views, and glimpses of local wildlife. With a gentle elevation gain of 45 feet, the trail provides a pleasant and accessible walking experience for individuals of all ages and fitness levels. Whether you're seeking a peaceful nature walk or a chance to admire the beauty of the falls, the Great Falls Overlook Trail is a perfect choice.",  cover_photo="https://alttrails.s3.amazonaws.com/88.jpg")
    walking7 = Trail(
        trail_name='Yellow branch Falls Trail', park='Sumter National Forest', city='Walhalla', state='SC', lat=34.7648, lng=83.0640, category_id=4, length=3.1, elevation_gain=465, user_id=9, description="The Yellow Branch Falls Trail, situated in Sumter National Forest near Walhalla, SC, is a scenic walking trail that leads to the beautiful Yellow Branch Falls. This 3.1-mile trail offers a moderate hike through a lush forest, treating visitors to the sights and sounds of nature along the way. As you traverse the trail, you'll encounter gentle slopes and a gradual elevation gain of 465 feet, making it suitable for hikers of various skill levels. The highlight of the trail is undoubtedly the picturesque Yellow Branch Falls, where a cascading waterfall tumbles over the rocks into a crystal-clear pool below. It's a perfect spot to rest, take in the natural beauty, and capture memorable photos. The Yellow Branch Falls Trail is a must-visit for nature enthusiasts and anyone seeking a peaceful outdoor experience.",  cover_photo="https://alttrails.s3.amazonaws.com/90.jpg")
    walking8 = Trail(
        trail_name='River Place Panther Hollow and Canyon Trail', park='National Preserve at River Place', city='West Lake Hills', state='TX', lat=30.2980, lng=97.8020, category_id=4, length=5.5, elevation_gain=823, user_id=8, description="The River Place Panther Hollow and Canyon Trail, located in the National Preserve at River Place in West Lake Hills, TX, offers a captivating walking experience through a diverse natural landscape. This 5.5-mile trail showcases the beauty of the area with its scenic views, lush vegetation, and enchanting water features. As you embark on the trail, you'll encounter various terrains, including the tranquil Panther Hollow and the rugged Canyon Trail. The elevation gain of 823 feet adds a touch of challenge, making it a satisfying hike for those seeking a moderate workout. Throughout the journey, you'll be surrounded by the sights and sounds of nature, including the soothing flow of creeks and the shade of towering trees. The River Place Panther Hollow and Canyon Trail is a fantastic choice for walkers looking to immerse themselves in the natural wonders of the preserve while enjoying a peaceful and invigorating outdoor experience.",  cover_photo="https://alttrails.s3.amazonaws.com/92.jpg")

    trails = [hiking1,
              hiking2,
              hiking3,
              hiking4,
              hiking5,
              hiking6,
              hiking7,
              hiking8,
              hiking9,
              hiking10,
              hiking11,
              hiking12,
              hiking13,
              hiking14,
              hiking15,
              biking1,
              biking2,
              biking3,
              biking4,
              biking5,
              biking6,
              biking7,
              biking8,
              biking9,
              biking10,
              biking11,
              biking12,
              running1,
              running2,
              running3,
              running4,
              running5,
              running6,
              running7,
              running8,
              walking1,
              walking2,
              walking3,
              walking4,
              walking5,
              walking6,
              walking7,
              walking8]

    [db.session.add(trail) for trail in trails]

    db.session.commit()


def undo_trails():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.trails RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM trails"))

    db.session.commit()
