"""empty message

Revision ID: 61b68701e1a5
Revises: 0b5d939cfd03
Create Date: 2023-06-22 12:48:04.021981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b68701e1a5'
down_revision = '0b5d939cfd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_photos', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_photos', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
